apiVersion: v1
kind: ConfigMap
metadata:
  name: web-v1
  annotations:
    # Protect this specific resource from being deleted during auto sync
    argocd.argoproj.io/sync-options: Prune=confirm
data:
  index.html: |
    <html><body><h1>Hello from V1</h1></body></html>
