apiVersion: v1
kind: Namespace
metadata:
  name: my-app-ns
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app-sa
  namespace: my-app-ns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: my-app-ns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  DB_ROOT_PASSWORD: dGhlcmVpc25vcGFzc3dvcmQK

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app-ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-app-sa
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_ROOT_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app-ns
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
